[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
name = "macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
ctor = "0.6.0"
darling = "0.21.3"
proc-macro2 = "1.0.102"
quote = "1.0.41"
syn = "2.0.108"
